name: Run Script on Schedule

on:
  schedule:
    # This cron expression runs the job every day at midnight (00:00 IST) -> (18:30 UTC)
    - cron: '30 18 * * *'
  workflow_dispatch: # This allows you to trigger the workflow manually from the GitHub Actions tab

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      # Step 3: Install dependencies if required
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run the Python script
      - name: Run script.py
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Set the environment variable using the secret
        run: python api/script.py
